version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: "xxxuserlocal"
      MYSQL_USER: "soerjo"
      MYSQL_PASSWORD: "soerjo123"
    ports:
      - "4100:3306"
